const all_steps = [
    {
        id: 1,
        title: "Learn the Basics",
        all_substeps: [{
            id: 1,
            substepTitle: "Language Basics",
            all_questions: [{
                id: 1,
                questionTitle: "User Input/Output",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/search-query-auto-complete/0?category%255B%255D=Strings&problemStatus=unsolved&difficulty%255B%255D=2&page=1&query=category%255B%255DStringsproblemStatusunsolveddifficulty%255B%255D2page1category%255B%255DStr",
                articlelink: "https://takeuforward.org/c/c-basic-input-output/",
            }, {
                id: 2,
                questionTitle: "Data Types",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/data-type-1666706751/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=data-type",
                articlelink: "",
            }, {
                id: 3,
                questionTitle: "If Else Statements",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/java-if-else-decision-making0924/0?category%255B%255D=Java&difficulty%255B%255D=-2&page=1&query=category%255B%255DJavadifficulty%255B%255D-2page1category%255B%255DJava",
                articlelink: "https://takeuforward.org/if-else/if-else-statements/",
            }, {
                id: 4,
                questionTitle: "Switch Statement",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/java-switch-case-statement3529/1",
                articlelink: "https://takeuforward.org/switch-case/switch-case-statements/",
            }, {
                id: 5,
                questionTitle: "What are Arrays, Strings?",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "",
                articlelink: "",
            }, {
                id: 6,
                questionTitle: "For Loops",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.naukri.com/code360/problems/nth-fibonacci-number_74156?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                articlelink: "https://takeuforward.org/for-loop/understanding-for-loop/",
            }, {
                id: 7,
                questionTitle: "While Loops",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/while-loop-printtable-java/1",
                articlelink: "https://takeuforward.org/while-loop/while-loops-in-programming/",
            }, {
                id: 8,
                questionTitle: "Functions",
                level: "easy",
                lecturelink: "https://youtu.be/EAR7De6Goz4",
                problemlink: "https://www.geeksforgeeks.org/problems/pass-by-reference-and-value/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=pass-by-reference-and-value",
                articlelink: "",
            }, {
                id: 9,
                questionTitle: "Time Complexity",
                level: "easy",
                lecturelink: "https://youtu.be/FPu9Uld7W-E",
                problemlink: "",
                articlelink: "https://takeuforward.org/time-complexity/time-and-space-complexity-strivers-a2z-dsa-course/"
            }]
        },
        {
            id: 2,
            substepTitle: "Build Up Logical Thinking",
            all_questions: [{
                id: 10,
                questionTitle: "Patterns",
                level: "easy",
                lecturelink: "https://youtu.be/tNm_NNSB3_w",
                problemlink: "",
                articlelink: "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/",
            }]
        }, {
            id: 3,
            substepTitle: "Learn STL",
            all_questions: [{
                id: 11,
                questionTitle: "C++ STL",
                level: "easy",
                lecturelink: "https://youtu.be/RRVYpIET_RU",
                problemlink: "",
                articlelink: "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/",
            }]
        }, {
            id: 4,
            substepTitle: "Know Basic Maths",
            all_questions: [{
                id: 12,
                questionTitle: "Count Digits",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://www.geeksforgeeks.org/problems/count-digits5716/1",
                articlelink: "https://takeuforward.org/data-structure/count-digits-in-a-number/",
            }, {
                id: 13,
                questionTitle: "Reverse a Number",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://leetcode.com/problems/reverse-integer/description/",
                articlelink: "https://takeuforward.org/maths/reverse-digits-of-a-number",
            }, {
                id: 14,
                questionTitle: "Check Palindrome",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://leetcode.com/problems/palindrome-number/description/",
                articlelink: "https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/",
            }, {
                id: 15,
                questionTitle: "GCD or HCF",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://www.geeksforgeeks.org/problems/lcm-and-gcd4516/1",
                articlelink: "https://takeuforward.org/data-structure/find-gcd-of-two-numbers/",
            }, {
                id: 16,
                questionTitle: "Armstrong Numbers",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://leetcode.com/problems/armstrong-number/description/",
                articlelink: "https://takeuforward.org/maths/check-if-a-number-is-armstrong-number-or-not/",
            }, {
                id: 17,
                questionTitle: "Print All Divisors",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://www.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1",
                articlelink: "https://takeuforward.org/data-structure/print-all-divisors-of-a-given-number/",
            }, {
                id: 18,
                questionTitle: "Check for Prime",
                level: "easy",
                lecturelink: "https://youtu.be/1xNbjMdbjug",
                problemlink: "https://www.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1",
                articlelink: "https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/",
            }]
        }, {
            id: 5,
            substepTitle: "Learn Basic Recursion",
            all_questions: [{
                id: 19,
                questionTitle: "Understanding Recursion by print something N times",
                level: "easy",
                lecturelink: "https://youtu.be/yVdKa8dnKiE",
                problemlink: "https://www.geeksforgeeks.org/problems/print-1-to-n-without-using-loops-1587115620/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=print-1-to-n-without-using-loops",
                articlelink: "https://takeuforward.org/recursion/introduction-to-recursion-understand-recursion-by-printing-something-n-times/",
            }, {
                id: 20,
                questionTitle: "Print name N times using recursion",
                level: "easy",
                lecturelink: "https://youtu.be/un6PLygfXrA",
                problemlink: "https://www.geeksforgeeks.org/problems/print-gfg-n-times/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=print-gfg-n-times",
                articlelink: "https://takeuforward.org/recursion/print-name-n-times-using-recursion/",
            }, {
                id: 21,
                questionTitle: "Print 1 to N using recursion",
                level: "easy",
                lecturelink: "https://youtu.be/un6PLygfXrA",
                problemlink: "https://www.geeksforgeeks.org/problems/print-1-to-n-without-using-loops-1587115620/1",
                articlelink: "https://takeuforward.org/recursion/print-1-to-n-using-recursion/",
            }, {
                id: 22,
                questionTitle: "Print N to 1 using recursion",
                level: "easy",
                lecturelink: "https://youtu.be/un6PLygfXrA",
                problemlink: "https://www.geeksforgeeks.org/problems/print-n-to-1-without-loop/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=print-n-to-1-without-loop",
                articlelink: "https://takeuforward.org/recursion/print-n-to-1-using-recursion/",
            }, {
                id: 23,
                questionTitle: "Sum of first N numbers",
                level: "easy",
                lecturelink: "https://youtu.be/69ZCDFy-OUo",
                problemlink: "https://www.geeksforgeeks.org/problems/sum-of-first-n-terms5843/1",
                articlelink: "https://takeuforward.org/data-structure/sum-of-first-n-natural-numbers/",
            }, {
                id: 24,
                questionTitle: "Factorial of N numbers",
                level: "easy",
                lecturelink: "https://youtu.be/69ZCDFy-OUo",
                problemlink: "https://www.geeksforgeeks.org/problems/find-all-factorial-numbers-less-than-or-equal-to-n3548/0?problemType=functional&difficulty%255B%255D=-1&page=1&query=problemTypefunctionaldifficulty%255B%255D-1page1",
                articlelink: "https://takeuforward.org/data-structure/factorial-of-a-number-iterative-and-recursive/",
            }, {
                id: 25,
                questionTitle: "Reverse an array",
                level: "easy",
                lecturelink: "https://youtu.be/twuC1F6gLI8",
                problemlink: "https://www.geeksforgeeks.org/problems/reverse-an-array/0",
                articlelink: "https://takeuforward.org/data-structure/reverse-a-given-array/",
            }, {
                id: 26,
                questionTitle: "Check if a string is palindrome or not",
                level: "medium",
                lecturelink: "https://youtu.be/twuC1F6gLI8",
                problemlink: "https://leetcode.com/problems/valid-palindrome/description/",
                articlelink: "https://takeuforward.org/data-structure/check-if-the-given-string-is-palindrome-or-not/",
            }, {
                id: 27,
                questionTitle: "Fibonacci number",
                level: "easy",
                lecturelink: "https://youtu.be/kvRjNm4rVBE",
                problemlink: "https://leetcode.com/problems/fibonacci-number/description/",
                articlelink: "https://takeuforward.org/arrays/print-fibonacci-series-up-to-nth-term/",
            }]
        }, {
            id: 6,
            substepTitle: "Learn Basic Hashing",
            all_questions: [{
                id: 28,
                questionTitle: "Hashing Theory",
                level: "medium",
                lecturelink: "https://youtu.be/KEs5UyBJ39g",
                problemlink: "",
                articlelink: "https://takeuforward.org/hashing/hashing-maps-time-complexity-collisions-division-rule-of-hashing-strivers-a2z-dsa-course/",
            }, {
                id: 29,
                questionTitle: "Counting frequencies of array elements",
                level: "easy",
                lecturelink: "",
                problemlink: "https://www.geeksforgeeks.org/problems/frequency-of-array-elements-1587115620/0",
                articlelink: "https://takeuforward.org/data-structure/count-frequency-of-each-element-in-the-array/",
            }, {
                id: 30,
                questionTitle: "Find the highest/lowest frequency element",
                level: "easy",
                lecturelink: "",
                problemlink: "https://leetcode.com/problems/frequency-of-the-most-frequent-element/description/",
                articlelink: "https://takeuforward.org/arrays/find-the-highest-lowest-frequency-element/",
            }]
        }]
    }, {
        id: 2,
        title: "Sorting Techniques",
        all_substeps: [{
            id: 1,
            substepTitle: "Sorting - I",
            all_questions: [{
                id: 31,
                questionTitle: "Selection Sort",
                level: "easy",
                lecturelink: "https://youtu.be/HGk_ypEuS24",
                problemlink: "https://www.geeksforgeeks.org/problems/selection-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=selection-sort",
                articlelink: "https://takeuforward.org/sorting/selection-sort-algorithm/",
            }, {
                id: 32,
                questionTitle: "Bubble Sort",
                level: "easy",
                lecturelink: "https://youtu.be/HGk_ypEuS24",
                problemlink: "https://www.geeksforgeeks.org/problems/bubble-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=bubble-sort",
                articlelink: "https://takeuforward.org/data-structure/bubble-sort-algorithm/",
            }, {
                id: 33,
                questionTitle: "Insertion Sort",
                level: "easy",
                lecturelink: "https://youtu.be/HGk_ypEuS24",
                problemlink: "https://www.geeksforgeeks.org/problems/insertion-sort/0?category%5B%5D=Algorithms&page=1&query=category%5B%5DAlgorithmspage1&utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=insertion-sort",
                articlelink: "https://takeuforward.org/data-structure/insertion-sort-algorithm/",
            }]
        }, {

            id: 2,
            substepTitle: "Sorting - II",
            all_questions: [{
                id: 34,
                questionTitle: "Merge Sort",
                level: "medium",
                lecturelink: "https://youtu.be/ogjf7ORKfd8",
                problemlink: "https://www.geeksforgeeks.org/problems/merge-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=merge-sort",
                articlelink: "https://takeuforward.org/data-structure/merge-sort-algorithm/",
            }, {
                id: 35,
                questionTitle: "Recursive Bubble Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "https://www.geeksforgeeks.org/problems/bubble-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=bubble-sort",
                articlelink: "https://takeuforward.org/arrays/recursive-bubble-sort-algorithm/",
            }, {
                id: 36,
                questionTitle: "Recursive Insertion Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "https://www.geeksforgeeks.org/problems/insertion-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=insertion-sort",
                articlelink: "https://takeuforward.org/arrays/recursive-insertion-sort-algorithm/",
            }, {
                id: 37,
                questionTitle: "Quick Sort",
                level: "easy",
                lecturelink: "https://youtu.be/WIrA4YexLRQ",
                problemlink: "https://www.geeksforgeeks.org/problems/quick-sort/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=quick-sort",
                articlelink: "https://takeuforward.org/data-structure/quick-sort-algorithm/",
            }]
        }]
    }, {
        id: 3,
        title: "Arrays",
        all_substeps: [{
            id: 1,
            substepTitle: "Arrays - I",
            all_questions: [{
                id: 38,
                questionTitle: "Largest Element in an array",
                level: "easy",
                lecturelink: "https://youtu.be/37E9ckMDdTk",
                problemlink: "https://www.geeksforgeeks.org/problems/largest-element-in-array4009/0?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=largest-element-in-array",
                articlelink: "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/",
            }, {
                id: 39,
                questionTitle: "Second Largest Element in an array without sorting",
                level: "easy",
                lecturelink: "https://youtu.be/37E9ckMDdTk",
                problemlink: "https://www.geeksforgeeks.org/problems/second-largest3735/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=second-largest",
                articlelink: "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/",
            }, {
                id: 40,
                questionTitle: "Check if array is sorted",
                level: "easy",
                lecturelink: "https://youtu.be/37E9ckMDdTk",
                problemlink: "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/description/",
                articlelink: "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/",
            }, {
                id: 41,
                questionTitle: "Remove Duplicates from Sorted array",
                level: "easy",
                lecturelink: "https://youtu.be/37E9ckMDdTk",
                problemlink: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/",
                articlelink: "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/",
            }, {
                id: 42,
                questionTitle: "Left rotate an array by one place",
                level: "easy",
                lecturelink: "https://youtu.be/wvcQg43_V8U",
                problemlink: "https://leetcode.com/problems/rotate-array/description/",
                articlelink: "https://takeuforward.org/data-structure/left-rotate-the-array-by-one/",
            }, {
                id: 43,
                questionTitle: "Left rotate an array by D places",
                level: "easy",
                lecturelink: "https://youtu.be/wvcQg43_V8U",
                problemlink: "https://leetcode.com/problems/rotate-array/description/",
                articlelink: "https://takeuforward.org/data-structure/rotate-array-by-k-elements/",
            }, {
                id: 44,
                questionTitle: "Move zeroes to end",
                level: "easy",
                lecturelink: "https://youtu.be/wvcQg43_V8U",
                problemlink: "https://leetcode.com/problems/move-zeroes/description/",
                articlelink: "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/",
            }, {
                id: 45,
                questionTitle: "Linear Search",
                level: "easy",
                lecturelink: "https://youtu.be/wvcQg43_V8U",
                problemlink: "https://www.geeksforgeeks.org/problems/who-will-win-1587115621/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=who-will-win",
                articlelink: "https://takeuforward.org/data-structure/linear-search-in-c/",
            }, {
                id: 46,
                questionTitle: "Find the Union",
                level: "medium",
                lecturelink: "https://youtu.be/wvcQg43_V8U",
                problemlink: "https://www.geeksforgeeks.org/problems/union-of-two-sorted-arrays-1587115621/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=union-of-two-sorted-arrays",
                articlelink: "https://takeuforward.org/data-structure/union-of-two-sorted-arrays/",
            }, {
                id: 47,
                questionTitle: "Find missing number in an array",
                level: "easy",
                lecturelink: "https://youtu.be/bYWLJb3vCWY",
                problemlink: "https://leetcode.com/problems/missing-number/description/",
                articlelink: "https://takeuforward.org/arrays/find-the-missing-number-in-an-array/",
            }, {
                id: 48,
                questionTitle: "Maximum Consecutive ones",
                level: "easy",
                lecturelink: "https://youtu.be/bYWLJb3vCWY",
                problemlink: "https://leetcode.com/problems/max-consecutive-ones/description/",
                articlelink: "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/",
            }, {
                id: 49,
                questionTitle: "Find the number that appears once, and other numbers twice",
                level: "medium",
                lecturelink: "https://youtu.be/bYWLJb3vCWY",
                problemlink: "https://leetcode.com/problems/single-number/description/",
                articlelink: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/",
            }, {
                id: 50,
                questionTitle: "Longest subarray with given sum K (positives)",
                level: "medium",
                lecturelink: "https://youtu.be/frf7qxiN2qU",
                problemlink: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=longest-sub-array-with-sum-k",
                articlelink: "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/",
            }, {
                id: 51,
                questionTitle: "Longest subarray with given sum K (positives + negatives)",
                level: "medium",
                lecturelink: "https://youtu.be/frf7qxiN2qU",
                problemlink: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=longest-sub-array-with-sum-k",
                articlelink: "https://takeuforward.org/arrays/longest-subarray-with-sum-k-postives-and-negatives/",
            }]
        }, {
            id: 2,
            substepTitle: "Arrays - II",
            all_questions: [{
                id: 52,
                questionTitle: "2 Sum Problem",
                level: "medium",
                lecturelink: "https://youtu.be/UXDSeD9mN-k",
                problemlink: "https://leetcode.com/problems/two-sum/description/",
                articlelink: "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/",

            }, {
                id: 53,
                questionTitle: "Sort an array of 0's, 1's and 2's",
                level: "medium",
                lecturelink: "https://youtu.be/tp8JIuCXBaU",
                problemlink: "https://leetcode.com/problems/sort-colors/description/",
                articlelink: "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/",

            }, {
                id: 54,
                questionTitle: "Majority Element (>n/2 times)",
                level: "easy",
                lecturelink: "https://youtu.be/nP_ns3uSh80",
                problemlink: "https://leetcode.com/problems/majority-element/description/",
                articlelink: "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/",

            }, {
                id: 55,
                questionTitle: "Kadane's Algorithm, maximum subarray sum",
                level: "easy",
                lecturelink: "https://youtu.be/w_KEocd__20",
                problemlink: "https://leetcode.com/problems/maximum-subarray/description/",
                articlelink: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",

            }, {
                id: 56,
                questionTitle: "Print subarray with maximum subarray sum (extended version of above problem)",
                level: "medium",
                lecturelink: "https://youtu.be/AHZpyENo7k4",
                problemlink: "https://www.geeksforgeeks.org/problems/max-sum-in-sub-arrays0824/0?category&utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=max-sum-in-sub-arrays",
                articlelink: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",

            }, {
                id: 57,
                questionTitle: "Stock Buy and Sell",
                level: "easy",
                lecturelink: "https://youtu.be/excAOvwF_Wk",
                problemlink: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/",
                articlelink: "https://takeuforward.org/data-structure/stock-buy-and-sell/",

            }, {
                id: 58,
                questionTitle: "Rearrange the array in alternating positive and negative items",
                level: "medium",
                lecturelink: "https://youtu.be/h4aBagy4Uok",
                problemlink: "https://leetcode.com/problems/rearrange-array-elements-by-sign/description/",
                articlelink: "https://takeuforward.org/arrays/rearrange-array-elements-by-sign/",

            }, {
                id: 59,
                questionTitle: "Next Permutation",
                level: "medium",
                lecturelink: "https://youtu.be/JDOXKqF60RQ",
                problemlink: "https://leetcode.com/problems/next-permutation/description/",
                articlelink: "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/",

            }, {
                id: 60,
                questionTitle: "Leaders in an Array problem",
                level: "easy",
                lecturelink: "https://youtu.be/cHrH9CQ8pmY",
                problemlink: "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=leaders-in-an-array",
                articlelink: "https://takeuforward.org/data-structure/leaders-in-an-array/",

            }, {
                id: 61,
                questionTitle: "Longest Consecutive Sequence in an Array",
                level: "medium",
                lecturelink: "https://youtu.be/oO5uLE7EUlM",
                problemlink: "https://leetcode.com/problems/longest-consecutive-sequence/editorial/",
                articlelink: "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/",

            }, {
                id: 62,
                questionTitle: "Set Matrix Zeros",
                level: "medium",
                lecturelink: "https://youtu.be/N0MgLvceX7M",
                problemlink: "https://leetcode.com/problems/set-matrix-zeroes/description/",
                articlelink: "https://takeuforward.org/data-structure/set-matrix-zero/",

            }, {
                id: 63,
                questionTitle: "Rotate Matrix by 90 degrees",
                level: "medium",
                lecturelink: "https://youtu.be/Z0R2u6gd3GU",
                problemlink: "https://leetcode.com/problems/rotate-image/description/",
                articlelink: "https://takeuforward.org/data-structure/rotate-image-by-90-degree/",

            }, {
                id: 64,
                questionTitle: "Print the matrix in spiral manner",
                level: "medium",
                lecturelink: "https://youtu.be/3Zv-s9UUrFM",
                problemlink: "https://leetcode.com/problems/spiral-matrix/description/",
                articlelink: "https://takeuforward.org/data-structure/spiral-traversal-of-matrix/",

            }, {
                id: 65,
                questionTitle: "Count subarrays with given sum",
                level: "easy",
                lecturelink: "https://youtu.be/xvNwoz-ufXA",
                problemlink: "https://leetcode.com/problems/subarray-sum-equals-k/description/",
                articlelink: "https://takeuforward.org/arrays/count-subarray-sum-equals-k/",

            }]
        }, {
            id: 3,
            substepTitle: "Arrays - III",
            all_questions: [{
                id: 66,
                questionTitle: "Pascal's Triangle",
                level: "medium",
                lecturelink: "https://youtu.be/bR7mQgwQ_o8",
                problemlink: "https://leetcode.com/problems/pascals-triangle/description/",
                articlelink: "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/",
            }, {
                id: 67,
                questionTitle: "Majority Element (n/3 times)",
                level: "medium",
                lecturelink: "https://youtu.be/vwZj1K0e9U8",
                problemlink: "https://leetcode.com/problems/majority-element-ii/description/",
                articlelink: "https://takeuforward.org/data-structure/majority-elementsn-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/",
            }, {
                id: 68,
                level: "medium",
                questionTitle: "3-Sum Problem",
                lecturelink: "https://youtu.be/DhFh8Kw7ymk",
                problemlink: "https://leetcode.com/problems/3sum/description/",
                articlelink: "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/",
            }, {
                id: 69,
                questionTitle: "4-Sum Problem",
                level: "hard",
                lecturelink: "https://youtu.be/eD95WRfh81c",
                problemlink: "https://leetcode.com/problems/4sum/description/",
                articlelink: "https://takeuforward.org/data-structure/4-sum-find-quads-that-add-up-to-a-target-value/",
            }, {
                id: 70,
                questionTitle: "Largest Subarray with 0 Sum",
                level: "medium",
                lecturelink: "https://youtu.be/xmguZ6GbatA",
                problemlink: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1?category%5B%5D=Hash&company%5B%5D=Amazon&page=1&query=category%5B%5DHashcompany%5B%5DAmazonpage1company%5B%5DAmazoncategory%5B%5DHash&utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=largest-subarray-with-0-sum",
                articlelink: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/",
            }, {
                id: 71,
                questionTitle: "Count number of subarrays with given xor K",
                level: "hard",
                lecturelink: "https://youtu.be/eZr-6p0B7ME",
                problemlink: "https://www.interviewbit.com/problems/subarray-with-given-xor/",
                articlelink: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/",
            }, {
                id: 72,
                questionTitle: "Merge Overlapping Subintervals",
                level: "medium",
                lecturelink: "https://youtu.be/IexN60k62jo",
                problemlink: "https://leetcode.com/problems/merge-intervals/description/",
                articlelink: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/",
            }, {
                id: 73,
                questionTitle: "Merge two sorted arrays without extra space",
                level: "medium",
                lecturelink: "https://youtu.be/n7uwj04E0I4",
                problemlink: "https://leetcode.com/problems/merge-sorted-array/",
                articlelink: "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/",
            }, {
                id: 74,
                questionTitle: "Find the repeating and missing number",
                level: "hard",
                lecturelink: "https://youtu.be/2D0D8HE6uak",
                problemlink: "https://www.geeksforgeeks.org/problems/find-missing-and-repeating2512/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=find-missing-and-repeating",
                articlelink: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/",
            }, {
                id: 75,
                questionTitle: "Count Inversions",
                level: "hard",
                lecturelink: "https://youtu.be/AseUmwVNaoY",
                problemlink: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=inversion-of-array",
                articlelink: "https://takeuforward.org/data-structure/count-reverse-pairs/",
            }, {
                id: 76,
                questionTitle: "Reverse Pairs",
                level: "hard",
                lecturelink: "https://youtu.be/0e4bZaP3MDI",
                problemlink: "https://leetcode.com/problems/reverse-pairs/description/",
                articlelink: "https://takeuforward.org/data-structure/count-reverse-pairs/",
            }, {
                id: 77,
                questionTitle: "Maximum Product Subarray",
                level: "easy",
                lecturelink: "https://youtu.be/hnswaLJvr6g",
                problemlink: "https://leetcode.com/problems/maximum-product-subarray/description/",
                articlelink: "https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/",
            }]
        }]
    }, {
        id: 4,
        title: "Binary Search",
        all_substeps: [{
            id: 1,
            substepTitle: "BS on 1D Arrays",
            all_questions: [{
                id: 78,
                questionTitle: "Binary Search to find X in sorted array",
                level: "easy",
                lecturelink: "https://youtu.be/MHf6awe89xw",
                problemlink: "https://leetcode.com/problems/binary-search/description/",
                articlelink: "https://takeuforward.org/data-structure/binary-search-explained/",
            }, {
                id: 79,
                questionTitle: "Implement Lower Bound",
                level: "easy",
                lecturelink: "https://youtu.be/6zhGS79oQ4k",
                problemlink: "https://www.geeksforgeeks.org/problems/floor-in-a-sorted-array-1587115620/1?track=DSASP-Searching&amp%253BbatchId=154&utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=floor-in-a-sorted-array",
                articlelink: "https://takeuforward.org/arrays/implement-lower-bound-bs-2/",
            }, {
                id: 80,
                questionTitle: "Implement Upper Bound",
                level: "easy",
                lecturelink: "https://youtu.be/6zhGS79oQ4k",
                problemlink: "https://www.geeksforgeeks.org/problems/ceil-the-floor2802/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=ceil-the-floor",
                articlelink: "https://takeuforward.org/arrays/implement-upper-bound/",
            }, {
                id: 81,
                questionTitle: "Search Insert Position",
                level: "easy",
                lecturelink: "https://youtu.be/6zhGS79oQ4k",
                problemlink: "https://leetcode.com/problems/search-insert-position/description/",
                articlelink: "https://takeuforward.org/arrays/search-insert-position/",
            }, {
                id: 82,
                questionTitle: "Floor/Ceil in Sorted Array",
                level: "medium",
                lecturelink: "https://youtu.be/6zhGS79oQ4k",
                problemlink: "https://www.naukri.com/code360/problems/ceiling-in-a-sorted-array_1825401",
                articlelink: "https://takeuforward.org/arrays/floor-and-ceil-in-sorted-array/",
            }, {
                id: 83,
                questionTitle: "Find the first or last occurrence of a given number in a sorted array",
                level: "easy",
                lecturelink: "https://youtu.be/hjR1IYVx9lY",
                problemlink: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/",
                articlelink: "https://takeuforward.org/data-structure/last-occurrence-in-a-sorted-array/",
            }, {
                id: 84,
                questionTitle: "Count occurrences of a number in a sorted array with duplicates",
                level: "easy",
                lecturelink: "https://youtu.be/hjR1IYVx9lY",
                problemlink: "https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=number-of-occurrence",
                articlelink: "https://takeuforward.org/data-structure/count-occurrences-in-sorted-array/",
            }, {
                id: 85,
                questionTitle: "Search in Rotated Sorted Array I",
                level: "medium",
                lecturelink: "https://youtu.be/5qGrJbHhqFs",
                problemlink: "https://leetcode.com/problems/search-in-rotated-sorted-array/description/",
                articlelink: "https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/",
            }, {
                id: 86,
                questionTitle: "Search in Rotated Sorted Array II",
                level: "medium",
                lecturelink: "https://youtu.be/w2G2W8l__pc",
                problemlink: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/",
                articlelink: "https://takeuforward.org/arrays/search-element-in-rotated-sorted-array-ii/",
            }, {
                id: 87,
                questionTitle: "Find minimum in Rotated Sorted Array",
                level: "medium",
                lecturelink: "https://youtu.be/nhEMDKMB44g",
                problemlink: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/",
                articlelink: "https://takeuforward.org/data-structure/minimum-in-rotated-sorted-array/",
            }, {
                id: 88,
                questionTitle: "Find out how many times has an array been rotated",
                level: "easy",
                lecturelink: "https://youtu.be/jtSiWTPLwd0",
                problemlink: "https://www.geeksforgeeks.org/problems/rotation4723/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=rotation",
                articlelink: "https://takeuforward.org/arrays/find-out-how-many-times-the-array-has-been-rotated/",
            }, {
                id: 89,
                questionTitle: "Single element in a Sorted Array",
                level: "easy",
                lecturelink: "https://youtu.be/AZOmHuHadxQ",
                problemlink: "https://leetcode.com/problems/single-element-in-a-sorted-array/description/",
                articlelink: "https://takeuforward.org/data-structure/search-single-element-in-a-sorted-array/",
            }, {
                id: 90,
                questionTitle: "Find peak element",
                level: "hard",
                lecturelink: "https://youtu.be/cXxmbemS6XM",
                problemlink: "https://leetcode.com/problems/find-peak-element/description/",
                articlelink: "https://takeuforward.org/data-structure/peak-element-in-array/",
            }]
        }, {
            id: 2,
            substepTitle: "BS on Answers",
            all_questions: [{
                id: 91,
                questionTitle: "Find square root of a number in log n",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 92,
                questionTitle: "Find the Nth root of a number using binary search",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 93,
                questionTitle: "Koko Eating Bananas",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 94,
                questionTitle: "Minimum days to make M bouquets",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 95,
                questionTitle: "Find the smallest Divisor",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 96,
                questionTitle: "Capacity to Ship Packages within D Days",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 97,
                questionTitle: "Kth Missing Positive Number",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 98,
                questionTitle: "Aggressive Cows",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 99,
                questionTitle: "Book Allocation Problem",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 100,
                questionTitle: "Split array - Largest Sum",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 101,
                questionTitle: "Painter's partition",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 102,
                questionTitle: "Minimize Max Distance to Gas Station",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 103,
                questionTitle: "Median of 2 sorted arrays",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 104,
                questionTitle: "Kth element of 2 sorted arrays",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 3,
            substepTitle: "BS on 2D Arrays",
            all_questions: [{
                id: 105,
                questionTitle: "Find the row with maximum number of 1's",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 106,
                questionTitle: "Search in a 2 D matrix",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 107,
                questionTitle: "Search in a row and column wise sorted matrix",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 108,
                questionTitle: "Find Peak Element (2D Matrix)",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 109,
                questionTitle: "Matrix Median",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    }, {
        id: 5,
        title: "Strings [Basic and Medium]",
        all_substeps: [{
            id: 1,
            substepTitle: "Basic and Easy String Problems",
            all_questions: [{
                id: 110,
                questionTitle: "Remove outermost Paranthesis",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 111,
                questionTitle: "Reverse words in a given string / Palindrome Check",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 112,
                questionTitle: "Largest odd number in a string",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 113,
                questionTitle: "Longest Common Prefix",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 114,
                questionTitle: "Isomorphic String",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 115,
                questionTitle: "Check whether one string is a rotation of another",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 116,
                questionTitle: "Check if two strings are anagram of each other",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Medium String Problems",
            all_questions: [{
                id: 117,
                questionTitle: "Sort Characters by frequency",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 118,
                questionTitle: "Maximum Nesting Depth of Paranthesis",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 119,
                questionTitle: "Roman Number to Integer and vice versa",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 120,
                questionTitle: "Implement Atoi",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 121,
                questionTitle: "Count Number of Substrings",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 122,
                questionTitle: "Longest Palindromic Substring[Do it without DP]",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 123,
                questionTitle: "Sum of Beauty of all substring",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 124,
                questionTitle: "Reverse Every Word in A String",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }],
    },
    // {
    //     id: 6,
    //     title: "Linked List",
    //     all_substeps: [{
    //         id: 1,
    //         substepTitle: "Learn 1D Linked List",
    //         all_questions: [{
    //             id: 125,
    //             questionTitle: "Introduction to LinkedList, learn about struct, and how is node represented",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 126,
    //             questionTitle: "Inserting a node in LinkedList",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 127,
    //             questionTitle: "Deleting a node in LinkedList",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 128,
    //             questionTitle: "Find the length of the linkedlist [learn traversal]",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 129,
    //             questionTitle: "Search an element in the LL",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }, {
    //         id: 2,
    //         substepTitle: "Learn Doubly Linked List",
    //         all_questions: [{
    //             id: 130,
    //             questionTitle: "Introduction to DLL, learn about struct, and how is node represented",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 131,
    //             questionTitle: "Insert a node in DLL",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 132,
    //             questionTitle: "Delete a node in DLL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 133,
    //             questionTitle: "Reverse a DLL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }, {
    //         id: 3,
    //         substepTitle: "Medium Problems of LL",
    //         all_questions: [{
    //             id: 134,
    //             questionTitle: "Middle of a LinkedList [TortoiseHare Method]",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 135,
    //             questionTitle: "Reverse a LinkedList [Iterative]",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 136,
    //             questionTitle: "Reverse a LL [Recursive]",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 137,
    //             questionTitle: "Detect a loop in LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 138,
    //             questionTitle: "Find the starting point in LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 139,
    //             questionTitle: "Length of Loop in LL",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 140,
    //             questionTitle: "Check if LL is palindrome or not",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 141,
    //             questionTitle: "Segrregate odd and even nodes in LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 142,
    //             questionTitle: "Remove Nth node from the back of the LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 143,
    //             questionTitle: "Delete the middle node of LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 144,
    //             questionTitle: "Sort LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 145,
    //             questionTitle: "Sort a LL of 0's 1's and 2's by changing links",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 146,
    //             questionTitle: "Find the intersection point of Y LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 147,
    //             questionTitle: "Add 1 to a number represented by LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 148,
    //             questionTitle: "Add 2 numbers in LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }, {
    //         id: 4,
    //         substepTitle: "Medium Problems of DLL",
    //         all_questions: [{
    //             id: 149,
    //             questionTitle: "Delete all occurrences of a key in DLL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 150,
    //             questionTitle: "Find pairs with given sum in DLL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 151,
    //             questionTitle: "Remove duplicates from sorted DLL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }, {
    //         id: 5,
    //         substepTitle: "Hard Problems of LL",
    //         all_questions: [{
    //             id: 152,
    //             questionTitle: "Reverse LL in group of given size K",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 153,
    //             questionTitle: "Rotate a LL",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 154,
    //             questionTitle: "Flattening of LL",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 155,
    //             questionTitle: "Clone a Linked List with random and next pointer",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }]
    // },
    // {
    //     id: 7,
    //     title: "Recursion [Patternwise]",
    //     all_substeps: [{
    //         id: 1,
    //         substepTitle: "Get a Strong Hold",
    //         all_questions: [{
    //             id: 156,
    //             questionTitle: "Recursive Implementation of atoi()",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 157,
    //             questionTitle: "Pow(x, n)",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 158,
    //             questionTitle: "Count Good numbers",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 159,
    //             questionTitle: "Sort a stack using recursion",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 160,
    //             questionTitle: "Reverse a stack using recursion",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }, {
    //         id: 2,
    //         substepTitle: "Subsequences Pattern",
    //         all_questions: [{
    //             id: 161,
    //             questionTitle: "Generate all binary strings",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 162,
    //             questionTitle: "Generate Paranthesis",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 163,
    //             questionTitle: "Print all subsequences/Power Set",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 164,
    //             questionTitle: "Learn All Patterns of Subsequences (Theory)",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 165,
    //             questionTitle: "Count all subsequences with sum K",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 166,
    //             questionTitle: "Check if there exists a subsequence with sum K",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",

    //         }, {
    //             id: 167,
    //             questionTitle: "Combination Sum",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 168,
    //             questionTitle: "Combination Sum - II",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 169,
    //             questionTitle: "Subset Sum - I",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",

    //         }, {
    //             id: 170,
    //             questionTitle: "Subset Sum - II",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",

    //         }, {
    //             id: 171,
    //             questionTitle: "Combination Sum - III",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",

    //         }, {
    //             id: 172,
    //             questionTitle: "Letter Combinations of a Phone Number",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",

    //         }]
    //     }, {
    //         id: 3,
    //         substepTitle: "Trying Out All Combos / Hard",
    //         all_questions: [{
    //             id: 173,
    //             questionTitle: "Palindrome Partioning",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 174,
    //             questionTitle: "Word Search",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 175,
    //             questionTitle: "N Queen",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 176,
    //             questionTitle: "Rat in a Maze",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 177,
    //             questionTitle: "Word Break",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 178,
    //             questionTitle: "M Coloring Problem",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 179,
    //             questionTitle: "Sudoko Solver",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 180,
    //             questionTitle: "Expression and Operators",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]

    //     }]
    // },
    // {
    //     id: 8,
    //     title: "Bit Manipulation [Concepts & Problems]",
    //     all_substeps: [{
    //         id: 1,
    //         substepTitle: "Get a Strong Hold",
    //         all_questions: [{
    //             id: 1,
    //             questionTitle: "Recursive Implementation of atoi()",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 2,
    //             questionTitle: "Pow(x, n)",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 3,
    //             questionTitle: "Count Good numbers",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 4,
    //             questionTitle: "Sort a stack using recursion",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 5,
    //             questionTitle: "Reverse a stack using recursion",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }]
    // }
    // }, {
    //     id: 9,
    //     title: "Stacks & Queues",
    //     color: "darkseagreen"
    // }, {
    //     id: 10,
    //     title: "Sliding Window & Two Pointer",
    //     color: "yellow"
    // }, {
    //     id: 11,
    //     title: "Heaps",
    //     color: "violet"
    // }, {
    //     id: 12,
    //     title: "Greedy Algorithms",
    //     color: "brown"
    // }, {
    //     id: 13,
    //     title: "Binary Trees",
    //     color: "hotpink"
    // }, {
    //     id: 14,
    //     title: "Binary Search Trees",
    //     color: "skyblue"
    // }, {
    //     id: 15,
    //     title: "Graphs",
    //     color: "orangered"
    // },
    // , {
    //     id: 16,
    //     title: "Dynamic Programming",
    //     color: "powderblue"
    // },
    // , {
    //     id: 17,
    //     title: "Tries",
    //     color: "royalblue"
    // }
];

export default all_steps;