const all_steps = [
    {
        id: 1,
        title: "Learn the Basics",
        all_substeps: [{
            id: 1,
            substepTitle: "Language Basics",
            all_questions: [{
                id: 1,
                questionTitle: "User Input/Output",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 2,
                questionTitle: "Data Types",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 3,
                questionTitle: "If Else Statements",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 4,
                questionTitle: "Switch Statement",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 5,
                questionTitle: "What are Arrays, Strings?",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 6,
                questionTitle: "For Loops",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 7,
                questionTitle: "While Loops",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 8,
                questionTitle: "Functions",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 9,
                questionTitle: "Time Complexity",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Build Up Logical Thinking",
            all_questions: [{
                id: 10,
                questionTitle: "Patterns",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 3,
            substepTitle: "Learn STL",
            all_questions: [{
                id: 11,
                questionTitle: "C++ STL",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 4,
            substepTitle: "Know Basic Maths",
            all_questions: [{
                id: 12,
                questionTitle: "Count Digits",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 13,
                questionTitle: "Reverse a Number",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 14,
                questionTitle: "Check Palindrome",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 15,
                questionTitle: "GCD or HCF",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 16,
                questionTitle: "Armstrong Numbers",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 17,
                questionTitle: "Print All Divisors",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 18,
                questionTitle: "Check for Prime",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 5,
            substepTitle: "Learn Basic Recursion",
            all_questions: [{
                id: 19,
                questionTitle: "Understanding Recursion by print something N times",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 20,
                questionTitle: "Print name N times using recursion",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 21,
                questionTitle: "Print 1 to N using recursion",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 22,
                questionTitle: "Print N to 1 using recursion",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 23,
                questionTitle: "Sum of first N numbers",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 24,
                questionTitle: "Factorial of N numbers",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 25,
                questionTitle: "Reverse an array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 26,
                questionTitle: "Check if a string is palindrome or not",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 27,
                questionTitle: "Fibonacci number",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 6,
            substepTitle: "Learn Basic Hashing",
            all_questions: [{
                id: 28,
                questionTitle: "Hashing Theory",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 29,
                questionTitle: "Counting frequencies of array elements",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 30,
                questionTitle: "Find the highest/lowest frequency element",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    }, {
        id: 2,
        title: "Sorting Techniques",
        all_substeps: [{
            id: 1,
            substepTitle: "Sorting - I",
            all_questions: [{
                id: 31,
                questionTitle: "Selection Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 32,
                questionTitle: "Bubble Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 33,
                questionTitle: "Insertion Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {

            id: 2,
            substepTitle: "Sorting - II",
            all_questions: [{
                id: 34,
                questionTitle: "Merge Sort",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 35,
                questionTitle: "Recursive Bubble Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 36,
                questionTitle: "Recursive Insertion Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 37,
                questionTitle: "Quick Sort",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    },
    {
        id: 3,
        title: "Arrays",
        all_substeps: [{
            id: 1,
            substepTitle: "Arrays - I",
            all_questions: [{
                id: 38,
                questionTitle: "Largest Element in an array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 39,
                questionTitle: "Second Largest Element in an array without sorting",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 40,
                questionTitle: "Check if array is sorted",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 41,
                questionTitle: "Remove Duplicates from Sorted array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 42,
                questionTitle: "Left rotate an array by one place",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 43,
                questionTitle: "Left rotate an array by D places",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 44,
                questionTitle: "Move zeroes to end",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 45,
                questionTitle: "Linear Search",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 46,
                questionTitle: "Find the Union",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 47,
                questionTitle: "Find missing number in an array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 48,
                questionTitle: "Maximum Consecutive ones",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 49,
                questionTitle: "Find the number that appears once, and other numbers twice",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 50,
                questionTitle: "Longest subarray with given sum K (positives)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 51,
                questionTitle: "Longest subarray with given sum K (positives + negatives)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Arrays - II",
            all_questions: [{
                id: 52,
                questionTitle: "2 Sum Problem",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 53,
                questionTitle: "Sort an array of 0's, 1's and 2's",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 54,
                questionTitle: "Majority Element (>n/2 times)",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 55,
                questionTitle: "Kadane's Algorithm, maximum subarray sum",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 56,
                questionTitle: "Print subarray with maximum subarray sum (extended version of above problem)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 57,
                questionTitle: "Stock Buy and Sell",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 58,
                questionTitle: "Rearrange the array in alternating positive and negative items",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 59,
                questionTitle: "Next Permutation",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 60,
                questionTitle: "Leaders in an Array problem",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 61,
                questionTitle: "Longest Consecutive Sequence in an Array",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 62,
                questionTitle: "Set Matrix Zeros",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 63,
                questionTitle: "Rotate Matrix by 90 degrees",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 64,
                questionTitle: "Print the matrix in spiral manner",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 65,
                questionTitle: "Count subarrays with given sum",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }]
        }, {
            id: 3,
            substepTitle: "Arrays - III",
            all_questions: [{
                id: 66,
                questionTitle: "Pascal's Triangle",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 67,
                questionTitle: "Majority Element (n/3 times)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 68,
                level: "medium",
                questionTitle: "3-Sum Problem",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 69,
                questionTitle: "4-Sum Problem",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 70,
                questionTitle: "Largest Subarray with 0 Sum",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 71,
                questionTitle: "Count number of subarrays with given xor K",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 72,
                questionTitle: "Merge Overlapping Subintervals",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 73,
                questionTitle: "Merge two sorted arrays without extra space",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 74,
                questionTitle: "Find the repeating and missing number",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 75,
                questionTitle: "Count Inversions",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 76,
                questionTitle: "Reverse Pairs",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 77,
                questionTitle: "Maximum Product Subarray",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    },
    {
        id: 4,
        title: "Binary Search",
        all_substeps: [{
            id: 1,
            substepTitle: "BS on 1D Arrays",
            all_questions: [{
                id: 78,
                questionTitle: "Binary Search to find X in sorted array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 79,
                questionTitle: "Implement Lower Bound",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 80,
                questionTitle: "Implement Upper Bound",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 81,
                questionTitle: "Search Insert Position",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 82,
                questionTitle: "Floor/Ceil in Sorted Array",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 83,
                questionTitle: "Find the first or last occurrence of a given number in a sorted array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 84,
                questionTitle: "Count occurrences of a number in a sorted array with duplicates",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 85,
                questionTitle: "Search in Rotated Sorted Array I",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 86,
                questionTitle: "Search in Rotated Sorted Array II",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 87,
                questionTitle: "Find minimum in Rotated Sorted Array",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 88,
                questionTitle: "Find out how many times has an array been rotated",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 89,
                questionTitle: "Single element in a Sorted Array",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 90,
                questionTitle: "Find peak element",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "BS on Answers",
            all_questions: [{
                id: 91,
                questionTitle: "Find square root of a number in log n",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 92,
                questionTitle: "Find the Nth root of a number using binary search",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 93,
                questionTitle: "Koko Eating Bananas",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 94,
                questionTitle: "Minimum days to make M bouquets",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 95,
                questionTitle: "Find the smallest Divisor",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 96,
                questionTitle: "Capacity to Ship Packages within D Days",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 97,
                questionTitle: "Kth Missing Positive Number",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 98,
                questionTitle: "Aggressive Cows",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 99,
                questionTitle: "Book Allocation Problem",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 100,
                questionTitle: "Split array - Largest Sum",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 101,
                questionTitle: "Painter's partition",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 102,
                questionTitle: "Minimize Max Distance to Gas Station",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 103,
                questionTitle: "Median of 2 sorted arrays",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 104,
                questionTitle: "Kth element of 2 sorted arrays",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 3,
            substepTitle: "BS on 2D Arrays",
            all_questions: [{
                id: 105,
                questionTitle: "Find the row with maximum number of 1's",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 106,
                questionTitle: "Search in a 2 D matrix",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 107,
                questionTitle: "Search in a row and column wise sorted matrix",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 108,
                questionTitle: "Find Peak Element (2D Matrix)",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 109,
                questionTitle: "Matrix Median",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    },
    {
        id: 5,
        title: "Strings [Basic and Medium]",
        all_substeps: [{
            id: 1,
            substepTitle: "Basic and Easy String Problems",
            all_questions: [{
                id: 110,
                questionTitle: "Remove outermost Paranthesis",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 111,
                questionTitle: "Reverse words in a given string / Palindrome Check",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 112,
                questionTitle: "Largest odd number in a string",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 113,
                questionTitle: "Longest Common Prefix",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 114,
                questionTitle: "Isomorphic String",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 115,
                questionTitle: "Check whether one string is a rotation of another",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 116,
                questionTitle: "Check if two strings are anagram of each other",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Medium String Problems",
            all_questions: [{
                id: 117,
                questionTitle: "Sort Characters by frequency",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 118,
                questionTitle: "Maximum Nesting Depth of Paranthesis",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 119,
                questionTitle: "Roman Number to Integer and vice versa",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 120,
                questionTitle: "Implement Atoi",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 121,
                questionTitle: "Count Number of Substrings",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 122,
                questionTitle: "Longest Palindromic Substring[Do it without DP]",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 123,
                questionTitle: "Sum of Beauty of all substring",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 124,
                questionTitle: "Reverse Every Word in A String",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }],
    },
    {
        id: 6,
        title: "Linked List",
        all_substeps: [{
            id: 1,
            substepTitle: "Learn 1D Linked List",
            all_questions: [{
                id: 125,
                questionTitle: "Introduction to LinkedList, learn about struct, and how is node represented",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 126,
                questionTitle: "Inserting a node in LinkedList",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 127,
                questionTitle: "Deleting a node in LinkedList",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 128,
                questionTitle: "Find the length of the linkedlist [learn traversal]",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 129,
                questionTitle: "Search an element in the LL",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Learn Doubly Linked List",
            all_questions: [{
                id: 130,
                questionTitle: "Introduction to DLL, learn about struct, and how is node represented",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 131,
                questionTitle: "Insert a node in DLL",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 132,
                questionTitle: "Delete a node in DLL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 133,
                questionTitle: "Reverse a DLL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 3,
            substepTitle: "Medium Problems of LL",
            all_questions: [{
                id: 134,
                questionTitle: "Middle of a LinkedList [TortoiseHare Method]",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 135,
                questionTitle: "Reverse a LinkedList [Iterative]",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 136,
                questionTitle: "Reverse a LL [Recursive]",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 137,
                questionTitle: "Detect a loop in LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 138,
                questionTitle: "Find the starting point in LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 139,
                questionTitle: "Length of Loop in LL",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 140,
                questionTitle: "Check if LL is palindrome or not",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 141,
                questionTitle: "Segrregate odd and even nodes in LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 142,
                questionTitle: "Remove Nth node from the back of the LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 143,
                questionTitle: "Delete the middle node of LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 144,
                questionTitle: "Sort LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 145,
                questionTitle: "Sort a LL of 0's 1's and 2's by changing links",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 146,
                questionTitle: "Find the intersection point of Y LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 147,
                questionTitle: "Add 1 to a number represented by LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 148,
                questionTitle: "Add 2 numbers in LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 4,
            substepTitle: "Medium Problems of DLL",
            all_questions: [{
                id: 149,
                questionTitle: "Delete all occurrences of a key in DLL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 150,
                questionTitle: "Find pairs with given sum in DLL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 151,
                questionTitle: "Remove duplicates from sorted DLL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 5,
            substepTitle: "Hard Problems of LL",
            all_questions: [{
                id: 152,
                questionTitle: "Reverse LL in group of given size K",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 153,
                questionTitle: "Rotate a LL",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 154,
                questionTitle: "Flattening of LL",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 155,
                questionTitle: "Clone a Linked List with random and next pointer",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }]
    },
    {
        id: 7,
        title: "Recursion [Patternwise]",
        all_substeps: [{
            id: 1,
            substepTitle: "Get a Strong Hold",
            all_questions: [{
                id: 156,
                questionTitle: "Recursive Implementation of atoi()",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 157,
                questionTitle: "Pow(x, n)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 158,
                questionTitle: "Count Good numbers",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 159,
                questionTitle: "Sort a stack using recursion",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 160,
                questionTitle: "Reverse a stack using recursion",
                level: "easy",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Subsequences Pattern",
            all_questions: [{
                id: 161,
                questionTitle: "Generate all binary strings",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 162,
                questionTitle: "Generate Paranthesis",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 163,
                questionTitle: "Print all subsequences/Power Set",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 164,
                questionTitle: "Learn All Patterns of Subsequences (Theory)",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 165,
                questionTitle: "Count all subsequences with sum K",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 166,
                questionTitle: "Check if there exists a subsequence with sum K",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 167,
                questionTitle: "Combination Sum",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 168,
                questionTitle: "Combination Sum - II",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 169,
                questionTitle: "Subset Sum - I",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 170,
                questionTitle: "Subset Sum - II",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 171,
                questionTitle: "Combination Sum - III",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }, {
                id: 172,
                questionTitle: "Letter Combinations of a Phone Number",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",

            }]
        }, {
            id: 3,
            substepTitle: "Trying Out All Combos / Hard",
            all_questions: [{
                id: 173,
                questionTitle: "Palindrome Partioning",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 174,
                questionTitle: "Word Search",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 175,
                questionTitle: "N Queen",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 176,
                questionTitle: "Rat in a Maze",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 177,
                questionTitle: "Word Break",
                level: "medium",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 178,
                questionTitle: "M Coloring Problem",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 179,
                questionTitle: "Sudoko Solver",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }, {
                id: 180,
                questionTitle: "Expression and Operators",
                level: "hard",
                lecturelink: "",
                problemlink: "",
                articlelink: "",
            }]

        }]
    },
    // {
    //     id: 8,
    //     title: "Bit Manipulation [Concepts & Problems]",
    //     all_substeps: [{
    //         id: 1,
    //         substepTitle: "Get a Strong Hold",
    //         all_questions: [{
    //             id: 1,
    //             questionTitle: "Recursive Implementation of atoi()",
    //             level: "hard",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 2,
    //             questionTitle: "Pow(x, n)",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 3,
    //             questionTitle: "Count Good numbers",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 4,
    //             questionTitle: "Sort a stack using recursion",
    //             level: "medium",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }, {
    //             id: 5,
    //             questionTitle: "Reverse a stack using recursion",
    //             level: "easy",
    //             lecturelink: "",
    //             problemlink: "",
    //             articlelink: "",
    //         }]
    //     }]
    // }
    // }, {
    //     id: 9,
    //     title: "Stacks & Queues",
    //     color: "darkseagreen"
    // }, {
    //     id: 10,
    //     title: "Sliding Window & Two Pointer",
    //     color: "yellow"
    // }, {
    //     id: 11,
    //     title: "Heaps",
    //     color: "violet"
    // }, {
    //     id: 12,
    //     title: "Greedy Algorithms",
    //     color: "brown"
    // }, {
    //     id: 13,
    //     title: "Binary Trees",
    //     color: "hotpink"
    // }, {
    //     id: 14,
    //     title: "Binary Search Trees",
    //     color: "skyblue"
    // }, {
    //     id: 15,
    //     title: "Graphs",
    //     color: "orangered"
    // },
    // , {
    //     id: 16,
    //     title: "Dynamic Programming",
    //     color: "powderblue"
    // },
    // , {
    //     id: 17,
    //     title: "Tries",
    //     color: "royalblue"
    // }
];

export default all_steps;