const all_steps = [
    {
        id: 1,
        title: "Basics",
        color: "aqua",
        all_substeps: [{
            id: 1,
            substepTitle: "Language Basics",
            all_questions: [{
                id: 1,
                questionTitle: "User Input/Output",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Data Types",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "If Else Statements",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Switch Statement",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "What are Arrays, Strings?",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "For Loops",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "While Loops",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Functions",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Time Complexity",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Build Up Logical Thinking",
            all_questions: [{
                id: 1,
                questionTitle: "Patterns",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 3,
            substepTitle: "Learn STL",
            all_questions: [{
                id: 1,
                questionTitle: "C++ STL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 4,
            substepTitle: "Know Basic Maths",
            all_questions: [{
                id: 1,
                questionTitle: "Count Digits",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Reverse a Number",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Check Palindrome",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "GCD or HCF",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Armstrong Numbers",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Print All Divisors",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Check for Prime",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 5,
            substepTitle: "Learn Basic Recursion",
            all_questions: [{
                id: 1,
                questionTitle: "Understanding Recursion by print something N times",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Print name N times using recursion",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Print 1 to N using recursion",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Print N to 1 using recursion",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Sum of first N numbers",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Factorial of N numbers",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Reverse an array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Check if a string is palindrome or not",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Fibonacci number",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 6,
            substepTitle: "Learn Basic Hashing",
            all_questions: [{
                id: 1,
                questionTitle: "Hashing Theory",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Counting frequencies of array elements",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Find the highest/lowest frequency element",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    }, {
        id: 2,
        title: "Sorting Techniques",
        color: "cadetblue",
        all_substeps: [{
            id: 1,
            substepTitle: "Sorting-I",
            all_questions: [{
                id: 1,
                questionTitle: "Selection Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Bubble Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Insertion Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {

            id: 2,
            substepTitle: "Sorting-II",
            all_questions: [{
                id: 1,
                questionTitle: "Merge Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Recursive Bubble Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Recursive Insertion Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Quick Sort",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    },
    {
        id: 3,
        title: "Arrays",
        color: "blueviolet",
        all_substeps: [{
            id: 1,
            substepTitle: "Arrays - I",
            all_questions: [{
                id: 1,
                questionTitle: "Largest Element in an array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Second Largest Element in an array without sorting",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Check if array is sorted",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Remove Duplicates from Sorted array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Left rotate an array by one place",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Left rotate an array by D places",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Move zeroes to end",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Linear Search",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Find the Union",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Find missing number in an array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Maximum Consecutive ones",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Find the number that appears once, and other numbers twice",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 13,
                questionTitle: "Longest subarray with given sum K (positives)",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 14,
                questionTitle: "Longest subarray with given sum K (positives + negatives)",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Arrays - II",
            all_questions: [{
                id: 1,
                questionTitle: "2 Sum Problem",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Sort an array of 0's, 1's and 2's",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Majority Element (>n/2 times)",
                solvelink: "",
                level: "easy",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Kadane's Algorithm, maximum subarray sum",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Print subarray with maximum subarray sum (extended version of above problem)",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Stock Buy and Sell",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Rearrange the array in alternating positive and negative items",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Next Permutation",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Leaders in an Array problem",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Longest Consecutive Sequence in an Array",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Set Matrix Zeros",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Rotate Matrix by 90 degrees",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 13,
                questionTitle: "Print the matrix in spiral manner",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 14,
                questionTitle: "Count subarrays with given sum",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 3,
            substepTitle: "Arrays - III",
            all_questions: [{
                id: 1,
                questionTitle: "Pascal's Triangle",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Majority Element (n/3 times)",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                level: "medium",
                questionTitle: "3-Sum Problem",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "4-Sum Problem",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Largest Subarray with 0 Sum",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Count number of subarrays with given xor K",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Merge Overlapping Subintervals",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Merge two sorted arrays without extra space",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Find the repeating and missing number",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Count Inversions",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Reverse Pairs",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Maximum Product Subarray",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    },
    {
        id: 4,
        title: "Binary Search",
        color: "chocolate",
        all_substeps: [{
            id: 1,
            substepTitle: "BS on 1D Arrays",
            all_questions: [{
                id: 1,
                questionTitle: "Binary Search to find X in sorted array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Implement Lower Bound",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Implement Upper Bound",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Search Insert Position",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Floor/Ceil in Sorted Array",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Find the first or last occurrence of a given number in a sorted array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Count occurrences of a number in a sorted array with duplicates",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Search in Rotated Sorted Array I",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Search in Rotated Sorted Array II",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Find minimum in Rotated Sorted Array",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Find out how many times has an array been rotated",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Single element in a Sorted Array",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 13,
                questionTitle: "Find peak element",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 2,
            substepTitle: "BS on Answers",
            all_questions: [{
                id: 1,
                questionTitle: "Find square root of a number in log n",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Find the Nth root of a number using binary search",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Koko Eating Bananas",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Minimum days to make M bouquets",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Find the smallest Divisor",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Capacity to Ship Packages within D Days",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Kth Missing Positive Number",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Aggressive Cows",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Book Allocation Problem",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Split array - Largest Sum",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Painter's partition",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Minimize Max Distance to Gas Station",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 13,
                questionTitle: "Median of 2 sorted arrays",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 14,
                questionTitle: "Kth element of 2 sorted arrays",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 3,
            substepTitle: "BS on 2D Arrays",
            all_questions: [{
                id: 1,
                questionTitle: "Find the row with maximum number of 1's",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Search in a 2 D matrix",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Search in a row and column wise sorted matrix",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Find Peak Element (2D Matrix)",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Matrix Median",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    },
    {
        id: 5,
        title: "Strings",
        color: "chartreuse",
        all_substeps: [{
            id: 1,
            substepTitle: "Basic and Easy String Problems",
            all_questions: [{
                id: 1,
                questionTitle: "Remove outermost Paranthesis",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Reverse words in a given string / Palindrome Check",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Largest odd number in a string",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Longest Common Prefix",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Isomorphic String",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Check whether one string is a rotation of another",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Check if two strings are anagram of each other",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Search in Rotated Sorted Array I",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Medium String Problems",
            all_questions: [{
                id: 1,
                questionTitle: "Sort Characters by frequency",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Maximum Nesting Depth of Paranthesis",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Roman Number to Integer and vice versa",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Implement Atoi",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Count Number of Substrings",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Longest Palindromic Substring[Do it without DP]",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Sum of Beauty of all substring",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Reverse Every Word in A String",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }],
    },
    {
        id: 6,
        title: "Linked List",
        color: "cornflowerblue",
        all_substeps: [{
            id: 1,
            substepTitle: "Learn 1D Linked List",
            all_questions: [{
                id: 1,
                questionTitle: "Introduction to LinkedList, learn about struct, and how is node represented",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Inserting a node in LinkedList",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Deleting a node in LinkedList",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Find the length of the linkedlist [learn traversal]",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Search an element in the LL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 2,
            substepTitle: "Learn Doubly Linked List",
            all_questions: [{
                id: 1,
                questionTitle: "Introduction to DLL, learn about struct, and how is node represented",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Insert a node in DLL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Delete a node in DLL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Reverse a DLL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 3,
            substepTitle: "Medium Problems of LL",
            all_questions: [{
                id: 1,
                questionTitle: "Middle of a LinkedList [TortoiseHare Method]",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Reverse a LinkedList [Iterative]",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Reverse a LL [Recursive]",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Detect a loop in LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 5,
                questionTitle: "Find the starting point in LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 6,
                questionTitle: "Length of Loop in LL",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 7,
                questionTitle: "Check if LL is palindrome or not",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 8,
                questionTitle: "Segrregate odd and even nodes in LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 9,
                questionTitle: "Remove Nth node from the back of the LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 10,
                questionTitle: "Delete the middle node of LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 11,
                questionTitle: "Sort LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 12,
                questionTitle: "Sort a LL of 0's 1's and 2's by changing links",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 13,
                questionTitle: "Find the intersection point of Y LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 14,
                questionTitle: "Add 1 to a number represented by LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 15,
                questionTitle: "Add 2 numbers in LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 4,
            substepTitle: "Medium Problems of DLL",
            all_questions: [{
                id: 1,
                questionTitle: "Delete all occurrences of a key in DLL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Find pairs with given sum in DLL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Remove duplicates from sorted DLL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }, {
            id: 5,
            substepTitle: "Hard Problems of LL",
            all_questions: [{
                id: 1,
                questionTitle: "Reverse LL in group of given size K",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 2,
                questionTitle: "Rotate a LL",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 3,
                questionTitle: "Flattening of LL",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }, {
                id: 4,
                questionTitle: "Clone a Linked List with random and next pointer",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    },
    {
        id: 7,
        title: "Recursion",
        color: "crimson",
        all_substeps:[{
            id: 1,
            substepTitle: "Get a Strong Hold",
            all_questions: [{
                id: 1,
                questionTitle: "Recursive Implementation of atoi()",
                level: "hard",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            },{
                id: 2,
                questionTitle: "Pow(x, n)",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            },{
                id: 3,
                questionTitle: "Count Good numbers",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            },{
                id: 4,
                questionTitle: "Sort a stack using recursion",
                level: "medium",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            },{
                id: 5,
                questionTitle: "Reverse a stack using recursion",
                level: "easy",
                solvelink: "",
                lecturelink: "",
                noteslink: "",
            }]
        }]
    },
    // }, {
    //     id: 8,
    //     title: "Bit Manipulation",
    //     color: "bisque"
    // }, {
    //     id: 9,
    //     title: "Stacks & Queues",
    //     color: "darkseagreen"
    // }, {
    //     id: 10,
    //     title: "Sliding Window & Two Pointer",
    //     color: "yellow"
    // }, {
    //     id: 11,
    //     title: "Heaps",
    //     color: "violet"
    // }, {
    //     id: 12,
    //     title: "Greedy Algorithms",
    //     color: "brown"
    // }, {
    //     id: 13,
    //     title: "Binary Trees",
    //     color: "hotpink"
    // }, {
    //     id: 14,
    //     title: "Binary Search Trees",
    //     color: "skyblue"
    // }, {
    //     id: 15,
    //     title: "Graphs",
    //     color: "orangered"
    // },
    // , {
    //     id: 16,
    //     title: "Dynamic Programming",
    //     color: "powderblue"
    // },
    // , {
    //     id: 17,
    //     title: "Tries",
    //     color: "royalblue"
    // }
];

export default all_steps;